// <auto-generated />
namespace WebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createinitialschema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createinitialschema));
        
        string IMigrationMetadata.Id
        {
            get { return "201608220134147_create-initial-schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
